<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <script>

        /*自己实现一个Promise
        */

        /*
自定义Promise函数模块：IIFE
 */

        //(function (window) {
        /*
        Promise构造函数
        executor:执行器函数
         */
        const PENDING = 'pending';
        const FULFILLED = 'fulfilled';
        const REJECTED = 'rejected';
        function Promise(executor) {
            let self = this;
            self.status = PENDING;
            self.onFulfilled = [];//成功的回调
            self.onRejected = []; //失败的回调
            //PromiseA+ 2.1
            function resolve(value) {
                if (self.status === PENDING) {
                    self.status = FULFILLED;
                    self.value = value;
                    self.onFulfilled.forEach(fn => fn());//PromiseA+ 2.2.6.1
                }
            }

            function reject(reason) {
                if (self.status === PENDING) {
                    self.status = REJECTED;
                    self.reason = reason;
                    self.onRejected.forEach(fn => fn());//PromiseA+ 2.2.6.2
                }
            }

            try {
                executor(resolve, reject);
            } catch (e) {
                reject(e);
            }
        }

        Promise.prototype.then = function (onFulfilled, onRejected) {
            onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
            onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason };
            let self = this;
            //执行完then是要返回一个新的promise的，而新的promise的状态则由当前then的执行结果来确定。
            let promise2 = new Promise((resolve, reject) => {

                /*
            调用指定回调函数的处理，根据执行结果。改变return的promise状态
             */
                function handle(callback) {
                    try {
                        const result = callback(self.value)
                        if (result instanceof Promise) {
                            // 2. 如果回调函数返回的是promise，return的promise的结果就是这个promise的结果
                            result.then(
                                value => { resolve(value) },
                                reason => { reject(reason) }
                            )
                        } else {
                            // 1. 如果回调函数返回的不是promise，return的promise的状态是resolved，value就是返回的值。
                            resolve(result)
                        }
                    } catch (e) {
                        //  3.如果执行onResolved的时候抛出错误，则返回的promise的状态为rejected
                        reject(e)
                    }
                }

                self.onFulfilled.push(() => {

                    if (self.status === FULFILLED) {
                        setTimeout(() => {
                            handle(onFulfilled);
                        });

                    }
                    else if (self.status === REJECTED) {
                        setTimeout(() => {
                            handle(onRejected);
                        });

                        // setTimeout(() => {
                        //     try {
                        //         let x = onRejected(self.reason);
                        //         //  resolvePromise(promise2, x, resolve, reject);
                        //     } catch (e) {
                        //         reject(e);
                        //     }
                        // });
                    }
                    else if (self.status === PENDING) {
                        self.onFulfilled.push(() => {
                            setTimeout(() => {
                                handle(onFulfilled);
                            });
                        });

                        self.onRejected.push(() => {
                            setTimeout(() => {
                                handle(onRejected);
                            });
                        });
                    }
                });

            });
            return promise2;
        };


        Promise.prototype.catch = function (onRejected) {
            return this.then(undefined, onRejected)
        };

        Promise.resolve = function (value) {
            return new Promise((resolve, reject) => {
                if (value instanceof Promise) {
                    // 如果value 是promise
                    value.then(
                        value => { resolve(value) },
                        reason => { reject(reason) }
                    )
                } else {
                    // 如果value不是promise
                    resolve(value)
                }

            });
        };

        Promise.all = function (promises) {
            const values = new Array(promises.length)
            var resolvedCount = 0 //计状态为resolved的promise的数量
            return new Promise((resolve, reject) => {
                // 遍历promises，获取每个promise的结果
                promises.forEach((p, index) => {
                    p.then(
                        value => {
                            // p状态为resolved，将值保存起来
                            values[index] = value
                            resolvedCount++;
                            // 如果全部p都为resolved状态，return的promise状态为resolved
                            if (resolvedCount === promises.length) {
                                resolve(values)
                            }
                        },
                        reason => { //只要有一个失败，return的promise状态就为reject
                            reject(reason)
                        }
                    )
                })
            })
        }
        /*
        Promise函数对象的reject方法
        返回一个指定reason的失败状态的promise对象
        */
        Promise.reject = function (reason) {
            return new Promise((resolve, reject) => {
                reject(reason)
            })
        }



        //test 
        let f1 = function (resolve, reject) {
            setTimeout(() => {
                resolve('123');
            }, 0);
        }

        function getUserId() {
            return new Promise(f1);
        }
        getUserId().then(function (id) {
            console.log('id', id);
        });


        setTimeout(() => { console.log('timeout 1000') }, 1000)


    </script>

</head>

<body>

</body>


</html>
<html>